### PR TITLE
Header & Sidebar Styling

### PR DESCRIPTION
**Pull request by wiafe**
Some styling for header and sidebar. Header had margin to the right of it, added clearfixes, and refactored some of the html. Content wasn't aligning properly on the sidebar, added clearfixes where it was needed and refactoring.

### CODE REVIEW

**Comment by crowdpublishtv** [comment]
Hi Randy. Thanks for fixing the alignment problem. 

The jpg/gif/png bookcovers are no longer aligning with the default bookcovers in author sidebars (note how they line up here).

Also, you added some bugs to the _forms that broke the author pages. Sign out of your app, view an author page, and observe the issue. Please debug & resubmit.

**Comment by wiafe** [comment]
@crowdpublishtv Hey, check out this https://github.com/wiafe/crowdpublishtv/commit/280897b82c15ff2a2c44c6674c6146982e481cbf

See if this fixes the issues.

**Comment by crowdpublishtv** [comment]
Your bug is in the _forms. Sign out and view one of the authors' home pages

On Wednesday, October 28, 2015, Randy Wiafe <notifications@github.com>
wrote:

> @crowdpublishtv <https://github.com/crowdpublishtv> Hey, check out this
> wiafe@280897b
> <https://github.com/wiafe/crowdpublishtv/commit/280897b82c15ff2a2c44c6674c6146982e481cbf>
>
> See if this fixes the issues.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/crowdpublishtv/crowdpublishtv/pull/58#issuecomment-151901667>
> .
>


-- 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Lisa Schaefer, Ph.D.  Chief Futurist
http://CrowdPublish.tv  ...like eBay for entrepreneurial authors - with
Live video
       The Future of Empowerment is Your Story

**Comment by wiafe** [comment]
@crowdpublishtv Is this the error you're talking about?

screen shot 2015-10-28 at 10 57 25 am

**Comment by crowdpublishtv** [comment]
Yes. Please change it back to @user. We want all users - authors AND
readers to be able to link to authors' Books and Live Event pages. We do
not, however, want links to Live Events etc. on readers' pages.

On Wednesday, October 28, 2015, Randy Wiafe <notifications@github.com>
wrote:

> @crowdpublishtv <https://github.com/crowdpublishtv> Is this the error
> you're talking about?
>
> [image: screen shot 2015-10-28 at 10 57 25 am]
> <https://cloud.githubusercontent.com/assets/7969131/10796212/d7ec68de-7d62-11e5-9e36-c5dce63c32d6.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/crowdpublishtv/crowdpublishtv/pull/58#issuecomment-151909439>
> .
>


-- 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Lisa Schaefer, Ph.D.  Chief Futurist
http://CrowdPublish.tv  ...like eBay for entrepreneurial authors - with
Live video
       The Future of Empowerment is Your Story

**Comment by wiafe** [comment]
When I do `@users` nothing shows up then : / or do I need to do something else?

**Comment by crowdpublishtv** [comment]
Nothing shows up where?

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Lisa Schaefer, Ph.D.  Chief Futurist
http://CrowdPublish.tv  ...like eBay for entrepreneurial authors - with
Live video
       The Future of Empowerment is Your Story

On Wed, Oct 28, 2015 at 2:37 PM, Randy Wiafe <notifications@github.com>
wrote:

> When I do @users nothing shows up then : / or do I need to do something
> else?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/crowdpublishtv/crowdpublishtv/pull/58#issuecomment-151945358>
> .
>

**Comment by crowdpublishtv** [comment]
Do you mean your authors have no books to display? That's probably because
your 'authors' didn't enter any of their books onto your computer. And/Or
you didn't create any authors.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Lisa Schaefer, Ph.D.  Chief Futurist
http://CrowdPublish.tv  ...like eBay for entrepreneurial authors - with
Live video
       The Future of Empowerment is Your Story

On Wed, Oct 28, 2015 at 3:58 PM, Lisa Schaefer <lisa@crowdpublish.tv> wrote:

> Nothing shows up where?
>
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> Lisa Schaefer, Ph.D.  Chief Futurist
> http://CrowdPublish.tv  ...like eBay for entrepreneurial authors - with
> Live video
>        The Future of Empowerment is Your Story
>
> On Wed, Oct 28, 2015 at 2:37 PM, Randy Wiafe <notifications@github.com>
> wrote:
>
>> When I do @users nothing shows up then : / or do I need to do something
>> else?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/crowdpublishtv/crowdpublishtv/pull/58#issuecomment-151945358>
>> .
>>
>
>

**Comment by wiafe** [comment]
@crowdpublishtv I have three authors created, and I went ahead and gave them all books. When I'm logged in as one author I can see the other authors books, when I'm not I get that error. Since I never changed any of the that code I don't know how to fix the problem, can you walk me through it?

**Comment by crowdpublishtv** [comment]
It's a simple fix, but I wanted you to be able to see the error & see how
you don't notice the error when you're logged in as an author.

Take a look at the current version of the file
https://github.com/crowdpublishtv/crowdpublishtv/blob/master/app/views/layouts/_authorform.html.erb

Then look at your commit to see where it changed
https://github.com/wiafe/crowdpublishtv/commit/5696c296d488f68819cb0107f9fa0a9e9ed8476f

Looks like the same problem is on the _editinfoform, which is a bug I
created, not you. You may wish to change that file too.

Here's a definition of current_user
http://stackoverflow.com/questions/12719958/rails-where-does-the-infamous-current-user-come-from
 When no one is logged in, current_user is nil.


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Lisa Schaefer, Ph.D.  Chief Futurist
http://CrowdPublish.tv  ...like eBay for entrepreneurial authors - with
Live video
       The Future of Empowerment is Your Story

On Fri, Oct 30, 2015 at 12:53 PM, Randy Wiafe <notifications@github.com>
wrote:

> @crowdpublishtv <https://github.com/crowdpublishtv> I have three authors
> created, and I went ahead and gave them all books. When I'm logged in as
> one author I can see the other authors books, when I'm not I get that
> error. Since I never changed any of the that code I don't know how to fix
> the problem, can you walk me through it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/crowdpublishtv/crowdpublishtv/pull/58#issuecomment-152585088>
> .
>

**Comment by wiafe** [comment]
@crowdpublishtv  ah ok, now I get it. Thank you for the help.

**Comment by wiafe** [comment]
@crowdpublishtv What's the best way for me to pull your changes?

**Comment by crowdpublishtv** [comment]
You can delete any files on your system where you made changes but liked my
changes better. For those files that you have made some changes you'd like
to keep, you could move those files out of your local app, pull my changes,
and paste your changes into the pulled files. For those files that I
changed and you didn't touch, no need to worry about those, the changes
will get pulled.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Lisa Schaefer, Ph.D.  Chief Futurist
http://CrowdPublish.tv  ...like eBay for entrepreneurial authors - with
Live video
       The Future of Empowerment is Your Story

On Fri, Oct 30, 2015 at 6:08 PM, Randy Wiafe <notifications@github.com>
wrote:

> @crowdpublishtv <https://github.com/crowdpublishtv> What's the best way
> for me to pull your changes?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/crowdpublishtv/crowdpublishtv/pull/58#issuecomment-152661879>
> .
>

**Pull request closed without merging**
